# Generated by Django 4.1.6 on 2023-02-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('representante', models.CharField(max_length=255)),
                ('celular', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='unidades',
            field=models.CharField(choices=[('u', 'Unidades'), ('pc', 'Piezas')], default='u', max_length=2),
        ),
    ]
